### ISSUE TITLE
Review on 8th June 

### ISSUE THREAD

**Issue by jason-wanjohi** [MasterFacilityList/mfl_admin_web#128]
- [ ] CRUD (Excel checklist)
- [x] Use of MOH logo with 'Ministry of Health' written below court of arms
- [x] Logo USAID to go to a new tab
- [ ] Feedback for every action
- [ ] Show autocomplete on a tablet
- [ ] Optimize excel download
- [x] Open weekend and open during public holidays
- [ ] Add ward name to facility list and owner
- [x] Number of times a facility service has been rated
- [x] Fix facility-owners in county
- [x] Add facility types to dashboard
- [ ] Spreadsheet for responsiveness

**Comment by ngash** [comment]
- [ ] No `is_active` in any **creation** form
- [ ] Confirmation dialog before any "dangerous" action e.g delete
- [ ] All search results to be ordered by rank/score rather than reverse chronological

**Comment by ngash** [comment]
- [ ] Error communication to users
- [ ] Uniform styling for deletion dialogues
- [ ] label list of wards in constituency view
- [ ] constituency view page to follow design of other view/edit pages
- [ ] move **facility status** and **facility type** to setup module
- [ ] better reporting of errors in forms
- [ ] add errors to input fields ( contextualizing errors )
- [ ] review all form validations
- [ ]
